services:
  todoapp:
    build:
      context: ./Dockerfiles/app
    container_name: todoapp
    ports:
      - "9067:9099"
    depends_on:
      - todomysql
    restart: always

  todomysql:
    image: mysql:8.0.33
    volumes:
      - tododbvol:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Welcome@12345
      - MYSQL_DATABASE=tododb

volumes:
  tododbvol: {}
