apiVersion: apps/v1
kind: Deployment
metadata:
  name: todoapp-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todoapp
  template:
    metadata:
      labels:
        app: todoapp # will be used by the selector in the appservice yaml
    spec:
      initContainers:
        - name: wait-for-mysql
          image: busybox
          command:
            - sh
            - -c
            - >
              until nslookup db-service.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local;
              do echo "Waiting for MySQL to be reachable..."; sleep 2; done;


      containers:
      - name: todoapp
        image: rahuldevsecops/todoapp
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - name: todoapp_port
          containerPort: 9099 
