apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  labels: 
    app: tododb
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard # if not specified, it will take default. Check with kubectl get storageclasss. Standard is most commanly used with cloud provided
  

